#ifndef GRAPHIC_ENGINE_HID_MOUSE_ENUM_KEYS_HPP
#define GRAPHIC_ENGINE_HID_MOUSE_ENUM_KEYS_HPP

namespace GraphicEngine::HID
{
	enum Button
	{
		BUTTON_LEFT,
		BUTTON_MIDDLE,
		BUTTON_RIGHT,
	};
}

#endif // !GRAPHIC_ENGINE_HID_MOUSE_ENUM_KEYS_HPP